flags: {}
packages:
- .
allow-newer: true
extra-deps:
- equational-reasoning-0.5.1.0
- ghc-typelits-presburger-0.2.0.0
- sized-0.3.0.0
- type-natural-0.8.0.0
- git: git@github.com:Daolab/hs-web3.git
  commit: 9ac6b925549e2f8eccb1b7fb86bd1eff001d7c17
- git: git@github.com:Daolab/beaker-preprocessor.git
  commit: 01aac494ec30cc0b55a9172d78debed16576cad6
resolver: lts-11.1
